package org.sworrl.beaconfix.link

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import org.sworrl.beaconfix.net.Bfs3
import org.sworrl.beaconfix.net.Bfs3Exception
import java.io.File

/**
 * Linking v3 against the normative vectors (`tests/fixtures/link_vectors.json`, generated by `tools/link_ref.py`):
 * code, MAC and the sealed payload byte for byte, tampering rejected, and the QR parsed as the PC prints it. The
 * repository copy is read when the tests run inside the checkout (a refined spec is picked up at once); the copy under
 * test resources is the fallback.
 */
class LinkTest {
    private val v: JsonObject by lazy {
        val repo = listOf("../../tests/fixtures/link_vectors.json", "../tests/fixtures/link_vectors.json", "tests/fixtures/link_vectors.json").map { File(it) }.firstOrNull { it.isFile }
        val text = repo?.readText() ?: javaClass.getResourceAsStream("/link_vectors.json")!!.bufferedReader().readText()
        Json.parseToJsonElement(text).jsonObject
    }
    private fun s(k: String) = v[k]!!.jsonPrimitive.content
    private fun b(k: String) = Bfs3.unb64u(s(k))
    private val sid get() = s("sid")
    private val shared get() = b("shared")

    private fun assertRejected(what: String, f: () -> Unit) {
        try { f(); fail("$what: accepted") } catch (e: Bfs3Exception) { /* expected */ }
    }
    private fun flipped(a: ByteArray, i: Int) = a.copyOf().also { it[i] = (it[i].toInt() xor 0x01).toByte() }

    @Test fun keysAndSharedSecret() {
        assertArrayEquals(b("pc_pub"), Bfs3.publicKey(b("pc_sk")))
        assertArrayEquals(b("phone_pub"), Bfs3.publicKey(b("phone_sk")))
        assertArrayEquals(shared, Bfs3.x25519(b("phone_sk"), b("pc_pub")))
        assertArrayEquals(shared, Bfs3.x25519(b("pc_sk"), b("phone_pub")))
    }

    @Test fun qrMac() {
        assertEquals(s("mac"), Link.mac(b("k"), sid, s("mac_name"), s("mac_kind"), s("phone_pub")))
        // every field is covered
        assertFalse(s("mac") == Link.mac(b("k"), sid, s("mac_name") + " ", s("mac_kind"), s("phone_pub")))
        assertFalse(s("mac") == Link.mac(b("k"), sid, s("mac_name"), "desktop", s("phone_pub")))
        assertFalse(s("mac") == Link.mac(b("k"), "a1b2c3d4e5f60719", s("mac_name"), s("mac_kind"), s("phone_pub")))
        assertFalse(s("mac") == Link.mac(flipped(b("k"), 0), sid, s("mac_name"), s("mac_kind"), s("phone_pub")))
    }

    @Test fun commitmentWhenTheVectorsHaveIt() {
        val c = v["commit"]?.jsonPrimitive?.content ?: return
        assertEquals(c, Link.commit(s("mac_name"), s("mac_kind"), s("phone_pub")))
    }

    @Test fun code() {
        assertEquals(s("code"), Link.code(shared, sid))
        assertEquals(6, Link.code(shared, sid).length)
        assertEquals(s("code").substring(0, 3) + " " + s("code").substring(3), Link.grouped(s("code")))
        assertFalse(s("code") == Link.code(shared, "a1b2c3d4e5f60719"))
        assertFalse(s("code") == Link.code(flipped(shared, 5), sid))
    }

    @Test fun sealedPayloadOpensToTheVector() {
        val opened = Link.openPayload(shared, sid, s("sealed"))
        assertEquals(s("payload"), String(opened, Charsets.UTF_8))
        assertEquals(s("sealed"), Link.sealPayload(shared, sid, b("nonce"), s("payload").toByteArray()))
        val p = Link.parsePayload(opened, 1)
        assertEquals("tok_example", p.token)
        assertEquals(listOf("read", "control"), p.scopes)
        assertEquals("desk-pc", p.pc.name)
        assertEquals(listOf("192.0.2.202"), p.pc.hosts)
        assertEquals(47897, p.pc.port)
        assertEquals("bfs3:example", p.hub)
    }

    @Test fun tamperedPayloadIsRejected() {
        val raw = b("sealed")
        for (i in listOf(0, 11, 12, raw.size / 2, raw.size - 17, raw.size - 1))
            assertRejected("byte $i flipped") { Link.openPayload(shared, sid, Bfs3.b64u(flipped(raw, i))) }
        assertRejected("another session") { Link.openPayload(shared, "a1b2c3d4e5f60719", s("sealed")) }
        assertRejected("another key") { Link.openPayload(flipped(shared, 0), sid, s("sealed")) }
        assertRejected("truncated") { Link.openPayload(shared, sid, Bfs3.b64u(raw.copyOf(raw.size - 1))) }
        assertRejected("too short") { Link.openPayload(shared, sid, Bfs3.b64u(raw.copyOf(20))) }
        assertRejected("not base64") { Link.openPayload(shared, sid, "%%%") }
    }

    @Test fun payloadWithoutTokenIsRefused() {
        assertRejected("no token") { Link.parsePayload("""{"scopes":["read"],"pc":{"name":"x"}}""".toByteArray(), 1) }
        assertRejected("not json") { Link.parsePayload("nope".toByteArray(), 1) }
        val p = Link.parsePayload("""{"token":"t","pc":{"name":"P","hosts":["fe80::1","10.0.0.2"]},"hub":null}""".toByteArray(), 47822)
        assertEquals(47822, p.pc.port); assertNull(p.hub); assertEquals(listOf("10.0.0.2"), p.pc.hosts); assertEquals(listOf("read", "control"), p.scopes)
    }

    @Test fun qrParses() {
        val q = Link.parseQr(s("qr"))
        assertEquals(sid, q.sid)
        assertEquals("desk-pc", q.name)
        assertEquals(listOf("192.0.2.202", "desk-pc.local"), q.hosts)
        assertEquals(47897, q.port)
        assertArrayEquals(b("pc_pub"), q.pcPub)
        assertArrayEquals(b("k"), q.k)
        assertEquals(1790900600L, q.expires)
        assertEquals("bfs3:example", q.hub)
        assertFalse(q.expired(1790900600L))
        assertTrue(q.expired(1790900600L + 3600))
        // as a scanner or a share sheet may hand it over: upper-case prefix, wrapped lines
        val wrapped = "BFLINK:" + s("qr").removePrefix("bflink:").chunked(40).joinToString("\n")
        assertEquals(q, Link.parseQr(wrapped))
        assertTrue(Link.classify(s("qr")) is Scanned.Link)
    }

    private fun qrOf(json: String) = "bflink:" + Bfs3.b64u(json.toByteArray())
    private val pub = Bfs3.b64u(ByteArray(32) { 9 }); private val k = Bfs3.b64u(ByteArray(32) { 7 })

    @Test fun badQrsAreRefused() {
        assertRejected("garbage") { Link.parseQr("bflink:!!!") }
        assertRejected("not json") { Link.parseQr(qrOf("hello")) }
        assertRejected("no sid") { Link.parseQr(qrOf("""{"v":1,"name":"P","hosts":["10.0.0.2"],"port":1,"pub":"$pub","k":"$k"}""")) }
        assertRejected("short sid") { Link.parseQr(qrOf("""{"v":1,"sid":"abc","hosts":["10.0.0.2"],"port":1,"pub":"$pub","k":"$k"}""")) }
        assertRejected("short key") { Link.parseQr(qrOf("""{"v":1,"sid":"a1b2c3d4e5f60718","hosts":["10.0.0.2"],"port":1,"pub":"AAAA","k":"$k"}""")) }
        assertRejected("short secret") { Link.parseQr(qrOf("""{"v":1,"sid":"a1b2c3d4e5f60718","hosts":["10.0.0.2"],"port":1,"pub":"$pub","k":"AAAA"}""")) }
        assertRejected("no host") { Link.parseQr(qrOf("""{"v":1,"sid":"a1b2c3d4e5f60718","hosts":[],"port":1,"pub":"$pub","k":"$k"}""")) }
        assertRejected("bad port") { Link.parseQr(qrOf("""{"v":1,"sid":"a1b2c3d4e5f60718","hosts":["10.0.0.2"],"port":70000,"pub":"$pub","k":"$k"}""")) }
        assertRejected("newer version") { Link.parseQr(qrOf("""{"v":2,"sid":"a1b2c3d4e5f60718","hosts":["10.0.0.2"],"port":1,"pub":"$pub","k":"$k"}""")) }
        assertRejected("another scheme") { Link.parseQr("https://example.com") }
        // a null hub, IPv6 link-local dropped, IPv4 first
        val q = Link.parseQr(qrOf("""{"v":1,"sid":"A1B2C3D4E5F60718","name":"P","hosts":["pc.local","fe80::1","192.168.1.5"],"port":47822,"pub":"$pub","k":"$k","e":0,"hub":null}"""))
        assertNull(q.hub); assertEquals(listOf("192.168.1.5", "pc.local"), q.hosts); assertEquals("a1b2c3d4e5f60718", q.sid); assertFalse(q.expired(Long.MAX_VALUE / 2))
        // non-ASCII names, raw UTF-8 or \u escapes, keys in any order
        assertEquals("Café PC", Link.parseQr(qrOf("""{"k":"$k","pub":"$pub","port":1,"hosts":["10.0.0.2"],"name":"Café PC","sid":"a1b2c3d4e5f60718","v":1}""")).name)
        assertEquals("Café PC", Link.parseQr(qrOf("""{"v":1,"sid":"a1b2c3d4e5f60718","name":"Caf\u00e9 PC","hosts":["10.0.0.2"],"port":1,"pub":"$pub","k":"$k"}""")).name)
    }

    @Test fun scannerClassifiesHubInvitesAndJunk() {
        val spk = Bfs3.publicKey(ByteArray(32) { (it + 1).toByte() })
        val invite = "bfs3:" + Bfs3.b64u("""{"u":"https://beacon.example.com/","s":"${Bfs3.b64u(spk)}","i":"0123456789abcdef","k":"$k","e":1790900600}""".toByteArray())
        val c = Link.classify(" $invite\n")
        assertTrue(c is Scanned.HubInvite)
        c as Scanned.HubInvite
        assertEquals(Bfs3.fingerprint(spk), c.invite.fingerprint)
        assertEquals("https://beacon.example.com/", c.invite.url)
        assertEquals(invite, c.text)
        assertTrue(Link.classify("BFID1:abc") is Scanned.Bad)
        assertTrue(Link.classify("bfs3:broken") is Scanned.Bad)
        assertTrue(Link.classify("bflink:broken") is Scanned.Bad)
        assertTrue(Link.classify("") is Scanned.Bad)
    }

    @Test fun hostsOrderAndValidity() {
        assertEquals(listOf("10.1.1.1", "192.168.1.50", "8.8.8.8", "100.64.0.1", "pc.local", "2001:db8::1"),
            Link.orderHosts(listOf("pc.local", "2001:db8::1", "100.64.0.1", "8.8.8.8", "10.1.1.1", "192.168.1.50")))
        assertFalse(Link.validHost("fe80::1%wlan0")); assertFalse(Link.validHost("fe80::1")); assertFalse(Link.validHost("127.0.0.1"))
        assertFalse(Link.validHost("bad host")); assertFalse(Link.validHost("a/b"))
        assertTrue(Link.validHost("192.168.1.2")); assertTrue(Link.validHost("pc.local")); assertTrue(Link.validHost("2001:db8::1"))
    }
}
