package org.sworrl.beaconfix.net

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.long
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import java.io.File

/**
 * BFS3 against the normative vectors (`tests/fixtures/bfs3_vectors.json`, generated by `tools/bfs3_ref.py`): every
 * value must match byte for byte. The repository copy is read when the tests run inside the checkout (so a refined
 * spec is picked up at once); the copy under test resources is the fallback.
 */
class Bfs3Test {
    private val v: JsonObject by lazy {
        val repo = listOf("../../tests/fixtures/bfs3_vectors.json", "../tests/fixtures/bfs3_vectors.json", "tests/fixtures/bfs3_vectors.json").map { File(it) }.firstOrNull { it.isFile }
        val text = repo?.readText() ?: javaClass.getResourceAsStream("/bfs3_vectors.json")!!.bufferedReader().readText()
        Json.parseToJsonElement(text).jsonObject
    }
    private fun s(o: JsonObject, k: String) = o[k]!!.jsonPrimitive.content
    private fun b(o: JsonObject, k: String) = Bfs3.unb64u(s(o, k))
    private val serverSk get() = b(v, "server_sk")
    private val serverPk get() = b(v, "server_pk")
    private val deviceSk get() = b(v, "device_sk")
    private val devicePk get() = b(v, "device_pk")
    private val did get() = s(v, "device_id")
    private val rk get() = b(v, "root_key")

    private fun assertRejected(what: String, f: () -> Unit) {
        try { f(); fail("$what: accepted") } catch (e: Bfs3Exception) { /* expected */ }
    }
    private fun flipped(a: ByteArray, i: Int) = a.copyOf().also { it[i] = (it[i].toInt() xor 0x01).toByte() }

    @Test fun keysFingerprintDeviceIdAndRootKey() {
        assertArrayEquals(serverPk, Bfs3.publicKey(serverSk))
        assertArrayEquals(devicePk, Bfs3.publicKey(deviceSk))
        assertEquals(s(v, "fingerprint"), Bfs3.fingerprint(serverPk))
        assertEquals(did, Bfs3.deviceId(devicePk))
        val shared = b(v, "shared")
        assertArrayEquals(shared, Bfs3.x25519(deviceSk, serverPk))
        assertArrayEquals(shared, Bfs3.x25519(serverSk, devicePk))
        assertArrayEquals(rk, Bfs3.rootKey(shared, serverPk, devicePk))
        assertArrayEquals(rk, Bfs3.rootKeyOf(deviceSk, serverPk))
        assertEquals(s(v, "server_pk"), Bfs3.b64u(serverPk))      // round trip, no padding
        assertEquals("aaa8 fff7 03b5 0b22 97f4 f6e1 3508 f724".length, Bfs3.groupedFingerprint(Bfs3.fingerprint(serverPk)).length)
    }

    @Test fun lowOrderPublicKeyIsRefused() {
        assertRejected("all-zero public key") { Bfs3.x25519(deviceSk, ByteArray(32)) }
    }

    @Test fun inviteParses() {
        val e = v["enroll"]!!.jsonObject
        val inv = Bfs3.parseInvite(s(e, "invite"))
        assertEquals("https://hub.example.com", inv.url)
        assertArrayEquals(serverPk, inv.serverPub)
        assertEquals(s(e, "invite_id"), inv.inviteId)
        assertArrayEquals(b(e, "invite_secret"), inv.secret)
        assertEquals(e["ts"]!!.jsonPrimitive.long + 900, inv.expires)
        assertEquals(s(v, "fingerprint"), inv.fingerprint)
        assertFalse(inv.expired(e["ts"]!!.jsonPrimitive.long))
        assertTrue(inv.expired(e["ts"]!!.jsonPrimitive.long + 901))
        // pasted with line breaks / spaces still reads
        val s0 = s(e, "invite"); assertEquals(inv.inviteId, Bfs3.parseInvite("  " + s0.substring(0, 40) + "\n" + s0.substring(40) + " ").inviteId)
    }

    @Test fun badInvitesAreRefused() {
        assertRejected("no prefix") { Bfs3.parseInvite("eyJ1IjoiaHR0cHM6Ly94In0") }
        assertRejected("garbage") { Bfs3.parseInvite("bfs3:!!!") }
        fun inv(json: String) = "bfs3:" + Bfs3.b64u(json.toByteArray())
        val k = Bfs3.b64u(ByteArray(32) { 1 })
        assertRejected("short key") { Bfs3.parseInvite(inv("""{"u":"https://h","s":"${Bfs3.b64u(ByteArray(31))}","i":"0123456789abcdef","k":"$k","e":1}""")) }
        assertRejected("bad id") { Bfs3.parseInvite(inv("""{"u":"https://h","s":"$k","i":"xyz","k":"$k","e":1}""")) }
        assertRejected("no url") { Bfs3.parseInvite(inv("""{"s":"$k","i":"0123456789abcdef","k":"$k","e":1}""")) }
    }

    @Test fun enrolMacAndProof() {
        val e = v["enroll"]!!.jsonObject
        val mac = Bfs3.enrollMac(b(e, "invite_secret"), s(e, "invite_id"), s(e, "name"), s(e, "kind"), s(v, "device_pk"), e["ts"]!!.jsonPrimitive.long)
        assertEquals(s(e, "mac"), mac)
        assertEquals(s(e, "proof"), Bfs3.proof(rk, did))
        assertTrue(Bfs3.checkProof(rk, did, s(e, "proof")))
        assertTrue(Bfs3.checkProof(rk, did, s(e, "proof").uppercase()))
        assertFalse(Bfs3.checkProof(rk, did, s(e, "proof").replaceRange(0, 1, if (s(e, "proof")[0] == '0') "1" else "0")))
        assertFalse(Bfs3.checkProof(rk, did + "x", s(e, "proof")))
        assertFalse(Bfs3.checkProof(Bfs3.rootKeyOf(Bfs3.newPrivateKey(), serverPk), did, s(e, "proof")))   // another device's rk
        // the MAC binds every field
        assertTrue(mac != Bfs3.enrollMac(b(e, "invite_secret"), s(e, "invite_id"), s(e, "name") + " ", s(e, "kind"), s(v, "device_pk"), e["ts"]!!.jsonPrimitive.long))
        assertTrue(mac != Bfs3.enrollMac(b(e, "invite_secret"), s(e, "invite_id"), s(e, "name"), s(e, "kind"), s(v, "device_pk"), e["ts"]!!.jsonPrimitive.long + 1))
    }

    @Test fun requestsMatchTheVectors() {
        val reqs = v["requests"]!!.jsonArray
        assertEquals(3, reqs.size)
        for (r0 in reqs) {
            val r = r0.jsonObject
            val c = r["counter"]!!.jsonPrimitive.long; val ts = r["ts"]!!.jsonPrimitive.long
            val m = s(r, "method"); val t = s(r, "target"); val nonce = b(r, "nonce"); val pt = s(r, "plaintext").toByteArray()
            assertArrayEquals("key c=$c", b(r, "key"), Bfs3.requestKey(rk, c))
            assertEquals("aad c=$c", s(r, "aad"), Bfs3.requestAad(m, t, did, c, ts))
            val sealed = Bfs3.sealRequest(rk, did, m, t, c, ts, nonce, pt)
            assertEquals("sealed c=$c", s(r, "sealed"), Bfs3.b64u(sealed))
            assertArrayEquals(pt, Bfs3.openRequest(rk, did, m, t, c, ts, nonce, sealed))
            // tamper: any bit of the ciphertext or tag, and every bound field
            for (i in sealed.indices) assertRejected("byte $i of c=$c") { Bfs3.openRequest(rk, did, m, t, c, ts, nonce, flipped(sealed, i)) }
            assertRejected("nonce") { Bfs3.openRequest(rk, did, m, t, c, ts, flipped(nonce, 0), sealed) }
            assertRejected("counter+1") { Bfs3.openRequest(rk, did, m, t, c + 1, ts, nonce, sealed) }
            assertRejected("ts+1") { Bfs3.openRequest(rk, did, m, t, c, ts + 1, nonce, sealed) }
            assertRejected("method") { Bfs3.openRequest(rk, did, if (m == "GET") "POST" else "GET", t, c, ts, nonce, sealed) }
            assertRejected("target") { Bfs3.openRequest(rk, did, m, "$t/x", c, ts, nonce, sealed) }
            assertRejected("device") { Bfs3.openRequest(rk, did.replaceRange(1, 2, "f"), m, t, c, ts, nonce, sealed) }
            assertRejected("truncated") { Bfs3.openRequest(rk, did, m, t, c, ts, nonce, sealed.copyOf(sealed.size - 1)) }
        }
        // the large counter is encoded as u64 big-endian in the key and in decimal in the AAD
        assertArrayEquals(byteArrayOf(0, 0, 1, 0, 0, 0, 0, 7), Bfs3.u64be((1L shl 40) + 7))
        assertEquals("bfs3\nGET\n/x\nd\n1099511627783\n0", Bfs3.requestAad("GET", "/x", "d", (1L shl 40) + 7, 0))
    }

    @Test fun responsesMatchTheVectors() {
        for (r0 in v["responses"]!!.jsonArray) {
            val r = r0.jsonObject
            val c = r["counter"]!!.jsonPrimitive.long; val status = r["status"]!!.jsonPrimitive.int
            val nonce = b(r, "nonce"); val pt = s(r, "plaintext").toByteArray()
            val sealed = Bfs3.sealResponse(rk, did, status, c, nonce, pt)
            assertEquals("sealed c=$c", s(r, "sealed"), Bfs3.b64u(sealed))
            assertArrayEquals(pt, Bfs3.openResponse(rk, did, status, c, nonce, sealed))
            assertArrayEquals(pt, Bfs3.openResponseFor(rk, did, c, status, c.toString(), s(r, "nonce"), sealed))
            assertRejected("counter is another request's") { Bfs3.openResponseFor(rk, did, c + 1, status, c.toString(), s(r, "nonce"), sealed) }
            assertRejected("no counter header") { Bfs3.openResponseFor(rk, did, c, status, null, s(r, "nonce"), sealed) }
            assertRejected("no nonce header") { Bfs3.openResponseFor(rk, did, c, status, c.toString(), null, sealed) }
            assertRejected("status changed") { Bfs3.openResponse(rk, did, if (status == 200) 401 else 200, c, nonce, sealed) }
            assertRejected("a request key does not open a response") { Bfs3.aead(false, Bfs3.requestKey(rk, c), nonce, Bfs3.responseAad(status, did, c).toByteArray(), sealed) }
            for (i in sealed.indices) assertRejected("byte $i") { Bfs3.openResponse(rk, did, status, c, nonce, flipped(sealed, i)) }
        }
    }

    @Test fun eventsMatchTheVectors() {
        val evs = v["events"]!!.jsonArray.map { it.jsonObject }
        for (e in evs) {
            val c = e["counter"]!!.jsonPrimitive.long; val seq = e["seq"]!!.jsonPrimitive.long
            val pt = s(e, "plaintext").toByteArray()
            assertEquals("line seq=$seq", s(e, "line"), Bfs3.sealEvent(rk, did, c, seq, b(e, "nonce"), pt))
            assertArrayEquals(pt, Bfs3.openEvent(rk, did, c, seq, s(e, "line")))
            assertArrayEquals(pt, Bfs3.openEvent(rk, did, c, seq, "data: " + s(e, "line")))
            assertRejected("another seq") { Bfs3.openEvent(rk, did, c, seq + 1, s(e, "line")) }
            assertRejected("another stream") { Bfs3.openEvent(rk, did, c + 1, seq, s(e, "line")) }
            val raw = Bfs3.unb64u(s(e, "line"))
            for (i in raw.indices) assertRejected("byte $i") { Bfs3.openEvent(rk, did, c, seq, Bfs3.b64u(flipped(raw, i))) }
            assertRejected("short") { Bfs3.openEvent(rk, did, c, seq, Bfs3.b64u(raw.copyOf(20))) }
        }
        // replayed / reordered events do not open under the next sequence number
        if (evs.size >= 2) assertRejected("event 1 replayed as 2") { Bfs3.openEvent(rk, did, 5, 2, s(evs[0], "line")) }
    }

    @Test fun roundTripWithFreshKeys() {
        val ssk = Bfs3.newPrivateKey(); val dsk = Bfs3.newPrivateKey()
        val rkD = Bfs3.rootKeyOf(dsk, Bfs3.publicKey(ssk))
        val rkS = Bfs3.rootKey(Bfs3.x25519(ssk, Bfs3.publicKey(dsk)), Bfs3.publicKey(ssk), Bfs3.publicKey(dsk))
        assertArrayEquals(rkD, rkS)
        val id = Bfs3.deviceId(Bfs3.publicKey(dsk)); val n = Bfs3.random(12)
        val body = "{\"lat\":1.5}".toByteArray()
        assertArrayEquals(body, Bfs3.openRequest(rkS, id, "POST", "/api/v3/devices/position", 9, 100, n, Bfs3.sealRequest(rkD, id, "POST", "/api/v3/devices/position", 9, 100, n, body)))
        assertEquals(25, id.length)
    }

    /** A store that can be told to fail, and records what was on "disk" when each counter was handed out. */
    private class MemStore(var disk: Long = 0) : CounterAllocator.Store {
        var failing = false; var writes = 0
        override fun reserved() = disk
        override fun reserve(upTo: Long) { if (failing) throw java.io.IOException("disk full"); disk = upTo; writes++ }
    }

    @Test fun countersStartAtOneGrowAndAreReservedBeforeUse() {
        val st = MemStore(); val a = CounterAllocator(st, block = 4)
        val got = (1..10).map { a.next().also { c -> assertTrue("counter $c used before it was reserved (disk ${st.disk})", c <= st.disk) } }
        assertEquals((1L..10L).toList(), got)
        assertEquals(3, st.writes)            // blocks 1–4, 5–8, 9–12
    }

    @Test fun aCrashNeverReusesACounter() {
        val st = MemStore(); val used = HashSet<Long>()
        repeat(5) { run ->                      // each "process" takes a few counters, then dies without any shutdown hook
            val a = CounterAllocator(st, block = 8)
            repeat(3 + run * 4) { val c = a.next(); assertTrue("counter $c reused", used.add(c)) }
        }
        assertEquals(1L, used.min())
    }

    @Test fun skippingAheadIsDurable() {
        val st = MemStore(); val a = CounterAllocator(st, block = 4)
        assertEquals(1L, a.next()); a.skip(256)
        val c = a.next(); assertEquals(258L, c); assertTrue(st.disk >= c)
        assertTrue(CounterAllocator(st, block = 4).next() > c)      // and a restart stays past it
    }

    @Test fun aFailedReservationHandsOutNothing() {
        val st = MemStore(); val a = CounterAllocator(st, block = 2)
        assertEquals(1L, a.next()); assertEquals(2L, a.next())
        st.failing = true
        try { a.next(); fail("counter handed out without a durable reservation") } catch (e: java.io.IOException) { /* expected */ }
        st.failing = false
        assertEquals(3L, a.next())
        assertTrue(st.disk >= 3)
    }
}
