#!/usr/bin/env python3
"""Render docs/battery-wiring.svg to the PNGs the desktop and Android apps show.

    tools/render_wiring.py        # needs PySide6 (pip install PySide6)

The SVG is the source; edit it, then rerun this. The node's own web page embeds the SVG
itself (firmware/esp32_node/WiringSvg.h, regenerated here too).
"""
import sys
from pathlib import Path

from PySide6.QtCore import QRectF, Qt
from PySide6.QtGui import QGuiApplication, QImage, QPainter
from PySide6.QtSvg import QSvgRenderer

ROOT = Path(__file__).resolve().parent.parent
SVG = ROOT / "docs/battery-wiring.svg"
OUTS = [ROOT / "data/hardware/battery-wiring.png",
        ROOT / "android/app/src/main/res/drawable-nodpi/battery_wiring.png"]
HEADER = ROOT / "firmware/esp32_node/WiringSvg.h"
SCALE = 2


def main() -> int:
    app = QGuiApplication(sys.argv[:1] + ["-platform", "offscreen"])
    renderer = QSvgRenderer(str(SVG))
    if not renderer.isValid():
        print(f"can't read {SVG}")
        return 1
    size = renderer.defaultSize() * SCALE
    img = QImage(size, QImage.Format_ARGB32)
    img.fill(Qt.transparent)
    p = QPainter(img)
    p.setRenderHint(QPainter.Antialiasing)
    p.setRenderHint(QPainter.TextAntialiasing)
    renderer.render(p, QRectF(0, 0, size.width(), size.height()))
    p.end()
    for out in OUTS:
        out.parent.mkdir(parents=True, exist_ok=True)
        img.save(str(out), "PNG")
        print(f"wrote {out.relative_to(ROOT)}")

    svg = " ".join(line.strip() for line in SVG.read_text().splitlines() if line.strip() and not line.strip().startswith("<!--"))
    HEADER.write_text("// Generated by tools/render_wiring.py from docs/battery-wiring.svg. Don't edit by hand.\n"
                      "#pragma once\n#include <pgmspace.h>\n\n"
                      f"static const char WIRING_SVG[] PROGMEM = R\"SVG({svg})SVG\";\n")
    print(f"wrote {HEADER.relative_to(ROOT)}")
    del app
    return 0


if __name__ == "__main__":
    sys.exit(main())
