#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
BeaconFix ESP32 Firmware Signing & Verification Tool.

Every install signs its own firmware. The ECDSA (secp256r1) keypair lives in tools/keys/, which git ignores;
the first --init (the flash scripts run it before every compile) creates it and writes the public half into
firmware/<board>/FwPublicKey.h, so the nodes you flash only accept OTA updates you signed.

    tools/sign_firmware.py --init                 # make the keypair if missing, refresh FwPublicKey.h
    tools/sign_firmware.py <firmware.bin>         # sign -> <firmware.bin>.sig
    tools/sign_firmware.py <firmware.bin> --verify
"""

import argparse
import hashlib
import os
import sys
from pathlib import Path
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec, utils
from cryptography.hazmat.backends import default_backend

DIR = Path(__file__).resolve().parent.parent
DEFAULT_KEY = DIR / "tools/keys/firmware_sign.key"
DEFAULT_PUB = DIR / "tools/keys/firmware_pub.pem"
FIRMWARE_TREES = ("esp32_node", "heltec_v3")


def ensure_keypair(key_path=DEFAULT_KEY, pub_path=DEFAULT_PUB) -> bytes:
    """Create the signing key on first use; (re)write the public key from it. Returns the public PEM."""
    key_path, pub_path = Path(key_path), Path(pub_path)
    if key_path.exists():
        private_key = serialization.load_pem_private_key(key_path.read_bytes(), password=None, backend=default_backend())
    else:
        key_path.parent.mkdir(parents=True, exist_ok=True)
        private_key = ec.generate_private_key(ec.SECP256R1(), default_backend())
        pem = private_key.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
                                        serialization.NoEncryption())
        fd = os.open(key_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(fd, "wb") as f:
            f.write(pem)
        print(f"[+] Generated a new firmware signing key: {key_path}")
        print("    Back it up. Nodes flashed with this key only take OTA updates signed by it.")
    pub_pem = private_key.public_key().public_bytes(serialization.Encoding.PEM,
                                                    serialization.PublicFormat.SubjectPublicKeyInfo)
    if not pub_path.exists() or pub_path.read_bytes() != pub_pem:
        pub_path.write_bytes(pub_pem)
    return pub_pem


def write_firmware_headers(pub_pem: bytes):
    """Embed the public key in each firmware tree (FwPublicKey.h, git-ignored)."""
    lines = "".join(f'"{line}\\n"\n' for line in pub_pem.decode().strip().splitlines())
    header = ("// Generated by tools/sign_firmware.py --init from tools/keys/firmware_pub.pem. Do not edit or commit:\n"
              "// each install has its own key, and nodes only accept OTA images signed by it.\n"
              "#pragma once\n"
              f"static const char* const FW_PUBLIC_KEY_PEM =\n{lines.rstrip()};\n")
    for tree in FIRMWARE_TREES:
        out = DIR / "firmware" / tree / "FwPublicKey.h"
        if not out.exists() or out.read_text() != header:
            out.write_text(header)
            print(f"[+] Wrote {out.relative_to(DIR)}")


def pub_key_body(pub_pem: bytes) -> list:
    return [l for l in pub_pem.decode().splitlines() if l and not l.startswith("-----")]


def sign_firmware(bin_path: str, key_path: str = DEFAULT_KEY, sig_path: str = None):
    bin_file = Path(bin_path)
    if not bin_file.exists():
        raise FileNotFoundError(f"Firmware binary not found: {bin_path}")
    if not Path(key_path).exists():
        raise FileNotFoundError(f"No signing key at {key_path}. Run tools/sign_firmware.py --init, then rebuild "
                                "the firmware so it embeds the new public key.")
    sig_path = sig_path or str(bin_file) + ".sig"

    private_key = serialization.load_pem_private_key(Path(key_path).read_bytes(), password=None,
                                                     backend=default_backend())
    data = bin_file.read_bytes()

    # A binary built before --init (or on another machine) trusts a different key: its nodes would reject
    # this signature, and every later OTA too
    pub_pem = private_key.public_key().public_bytes(serialization.Encoding.PEM,
                                                    serialization.PublicFormat.SubjectPublicKeyInfo)
    if not all(line.encode() in data for line in pub_key_body(pub_pem)):
        raise ValueError(f"{bin_path} doesn't embed this key's public half. Run tools/sign_firmware.py --init "
                         "and rebuild before signing.")

    digest = hashlib.sha256(data).digest()
    # The node runs mbedtls_pk_verify over this SHA-256 itself, so sign the digest as-is: ECDSA(SHA256()) would
    # hash it again and every OTA would be rejected
    signature = private_key.sign(digest, ec.ECDSA(utils.Prehashed(hashes.SHA256())))
    Path(sig_path).write_bytes(signature)

    print(f"[+] Signed firmware: {bin_path} ({len(data)} bytes)")
    print(f"[+] SHA256: {digest.hex()}")
    print(f"[+] Signature written to: {sig_path} ({len(signature)} bytes)")
    return True


def verify_firmware(bin_path: str, pub_path: str = DEFAULT_PUB, sig_path: str = None):
    sig_path = sig_path or str(bin_path) + ".sig"
    public_key = serialization.load_pem_public_key(Path(pub_path).read_bytes(), backend=default_backend())
    digest = hashlib.sha256(Path(bin_path).read_bytes()).digest()
    try:
        public_key.verify(Path(sig_path).read_bytes(), digest, ec.ECDSA(utils.Prehashed(hashes.SHA256())))
        print(f"[✓] Signature VALID! Verified with {pub_path}")
        return True
    except Exception as e:
        print(f"[✗] Signature INVALID: {e}", file=sys.stderr)
        return False


def main():
    p = argparse.ArgumentParser(description="Sign or verify ESP32 firmware binary")
    p.add_argument("binary", nargs="?", help="Path to firmware .bin file")
    p.add_argument("--init", action="store_true",
                   help="Create the signing keypair if missing and write firmware/*/FwPublicKey.h")
    p.add_argument("--key", default=str(DEFAULT_KEY), help="Private key path")
    p.add_argument("--pub", default=str(DEFAULT_PUB), help="Public key path")
    p.add_argument("--sig", default=None, help="Signature file path (default <binary>.sig)")
    p.add_argument("--verify", action="store_true", help="Verify signature instead of signing")
    args = p.parse_args()

    if args.init:
        write_firmware_headers(ensure_keypair(args.key, args.pub))
        if not args.binary:
            return
    if not args.binary:
        p.error("a firmware binary is required unless --init is given")

    if args.verify:
        sys.exit(0 if verify_firmware(args.binary, args.pub, args.sig) else 1)
    try:
        sign_firmware(args.binary, args.key, args.sig)
    except (FileNotFoundError, ValueError) as e:
        print(f"[✗] {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
